name: Continuous

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Update NPM registry
        run: npm run update:registry

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Format
        run: npm run format:check

      - name: Lint
        run: npm run lint:check

      - name: Spell Check
        run: npm run spell

      - name: Unit tests
        run: npm run test

  Component:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Update NPM registry
        run: npm run update:registry

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:e2e

      - name: Install Cypress
        run: npm run test:cy:install

      - name: Run Cypress
        uses: cypress-io/github-action@v4
        with:
          build: npm run cy:build
          start: npm run cy:start
          wait-on: 'http://localhost:3333'
          working-directory: packages/components
          install: false
          browser: chrome
          component: true
          env: type=actual
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Visual:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Update NPM registry
        run: npm run update:registry

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:e2e

      - name: Install Cypress
        run: npm run test:cy:install

      - name: Run Cypress
        uses: cypress-io/github-action@v4
        with:
          build: npm run cy:build
          start: npm run cy:start
          wait-on: 'http://localhost:3333'
          working-directory: packages/components
          install: false
          browser: chrome
          env: type=actual
          spec: |
            cypress/e2e/visual/*.cy.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload snapshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-snapshots
          path: packages/components/cypress/snapshots
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Performance:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Update NPM registry
        run: npm run update:registry

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:e2e

      - name: Install Cypress
        run: npm run test:cy:install

      - name: Run Cypress
        uses: cypress-io/github-action@v4
        with:
          build: npm run cy:build
          start: npm run cy:start
          wait-on: 'http://localhost:3333'
          working-directory: packages/components
          install: false
          browser: chrome
          headed: true
          spec: |
            cypress/e2e/perf/*.cy.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  TestingLib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Update NPM registry
        run: npm run update:registry

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build:e2e

      - name: Install Cypress
        run: npm run test:cy:install

      - name: Run Cypress
        uses: cypress-io/github-action@v4
        with:
          build: npm run cy:build
          start: npm run cy:start
          wait-on: 'http://localhost:3333'
          working-directory: packages/components
          install: false
          browser: chrome
          env: type=actual
          spec: |
            cypress/e2e/base/*.cy.ts
            cypress/e2e/legacy/*.cy.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  OutputTargets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Update npm registry
        run: npm run update:registry

      - name: Install dependencies
        run: npm ci

      - name: Angular build
        run: npm --prefix packages/output-targets/angular run build

      - name: Angular test
        run: npm --prefix packages/output-targets/angular run test

      - name: Vue build
        run: npm --prefix packages/output-targets/vue run build

      - name: Vue test
        run: npm --prefix packages/output-targets/vue run test

      - name: React build
        run: npm --prefix packages/output-targets/react run build

      - name: React test
        run: npm --prefix packages/output-targets/react run test
