name: Continuous

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  Build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Update NPM registry
        run: npm run registry

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build:force

      - name: Format
        run: npm run format:check

      - name: Lint
        run: npm run lint:check

      - name: Spell Check
        run: npm run spell

      - name: Unit tests
        run: npm run test

      - name: Check if there are changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11

      - name: Uncommitted changes
        if: steps.changes.outputs.changed == 1
        run: exit 1

  Component:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Update NPM registry
        run: npm run registry

      - name: Install dependencies
        run: npm install

      - name: Install Cypress
        run: npm run cy:install

      - name: Build
        run: npm run cy:build

      - name: Run Cypress
        uses: cypress-io/github-action@v4
        with:
          start: npm run cy:start
          wait-on: 'http://localhost:3333'
          working-directory: packages/components
          install: false
          browser: chrome
          component: true
          env: type=actual
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload snapshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-snapshots-components
          path: packages/components/cypress/snapshots
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload videos
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: packages/components/cypress/videos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Accessibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Update NPM registry
        run: npm run registry

      - name: Install dependencies
        run: npm install

      - name: Install Cypress
        run: npm run cy:install

      - name: Build
        run: npm run cy:build

      - name: Run Cypress
        uses: cypress-io/github-action@v4
        with:
          start: npm run cy:start
          wait-on: 'http://localhost:3333'
          working-directory: packages/components
          install: false
          browser: chrome
          env: type=actual
          spec: |
            cypress/e2e/a11y/*.cy.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload snapshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-snapshots-a11y
          path: packages/components/cypress/snapshots
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload videos
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: packages/components/cypress/videos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  VisualComponentsA:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Update NPM registry
        run: npm run registry

      - name: Install dependencies
        run: npm install

      - name: Install Cypress
        run: npm run cy:install

      - name: Build
        run: npm run cy:build

      - name: Run Cypress
        uses: cypress-io/github-action@v4
        with:
          start: npm run cy:start
          wait-on: 'http://localhost:3333'
          working-directory: packages/components
          install: false
          browser: chrome
          env: type=actual
          spec: |
            cypress/e2e/visual/bal-!(navigation|button|field|input-group|popover|select|radio|navbar|checkbox|tabs|card|datepicker).visual.cy.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload snapshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-snapshots-a
          path: packages/components/cypress/snapshots
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  VisualComponentsB:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Update NPM registry
        run: npm run registry

      - name: Install dependencies
        run: npm install

      - name: Install Cypress
        run: npm run cy:install

      - name: Build
        run: npm run cy:build

      - name: Run Cypress
        uses: cypress-io/github-action@v4
        with:
          start: npm run cy:start
          wait-on: 'http://localhost:3333'
          working-directory: packages/components
          install: false
          browser: chrome
          env: type=actual
          spec: |
            cypress/e2e/visual/bal-button.visual.cy.ts
            cypress/e2e/visual/bal-card.visual.cy.ts
            cypress/e2e/visual/bal-checkbox.visual.cy.ts
            cypress/e2e/visual/bal-datepicker.visual.cy.ts
            cypress/e2e/visual/bal-field.visual.cy.ts
            cypress/e2e/visual/bal-input-group.visual.cy.ts
            cypress/e2e/visual/bal-navbar.visual.cy.ts
            cypress/e2e/visual/bal-navigation.visual.cy.ts
            cypress/e2e/visual/bal-popover.visual.cy.ts
            cypress/e2e/visual/bal-radio.visual.cy.ts
            cypress/e2e/visual/bal-select.visual.cy.ts
            cypress/e2e/visual/bal-tabs.visual.cy.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload snapshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-snapshots-b
          path: packages/components/cypress/snapshots
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  VisualCSS:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Update NPM registry
        run: npm run registry

      - name: Install dependencies
        run: npm install

      - name: Install Cypress
        run: npm run cy:install

      - name: Build
        run: npm run cy:build

      - name: Run Cypress
        uses: cypress-io/github-action@v4
        with:
          start: npm run cy:start
          wait-on: 'http://localhost:3333'
          working-directory: packages/components
          install: false
          browser: chrome
          env: type=actual
          spec: |
            cypress/e2e/visual/css-*.cy.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload snapshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-snapshots
          path: packages/components/cypress/snapshots
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  TestingLib:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Update NPM registry
        run: npm run registry

      - name: Install dependencies
        run: npm install

      - name: Install Cypress
        run: npm run cy:install

      - name: Build
        run: npm run cy:build

      - name: Run Cypress
        uses: cypress-io/github-action@v4
        with:
          start: npm run cy:start
          wait-on: 'http://localhost:3333'
          working-directory: packages/components
          install: false
          browser: chrome
          env: type=actual
          spec: |
            cypress/e2e/base/*.cy.ts
            cypress/e2e/legacy/*.cy.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload snapshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-snapshots
          path: packages/components/cypress/snapshots
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload videos
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-videos
          path: packages/components/cypress/videos
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
