name: Documentation

on:
  workflow_run:
    workflows: ['Release']
    branches: [next]
    types:
      - completed
  workflow_dispatch:

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Declare some variables
        id: vars
        shell: bash
        run: |
          echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
          echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: baloise/design-system-docs:${{ steps.vars.outputs.sha_short }},baloise/design-system-docs:latest

      - name: Deploy
        uses: addnab/docker-run-action@v3
        with:
          image: baloise/gitopscli:5.4.0
          run: |
            gitopscli deploy \
            --git-provider-url https://github.com \
            --username ${{ secrets.GITHUB_ACTOR }} \
            --password ${{ secrets.GITHUB_TOKEN }} \
            --git-user "Baloise OpenSource Bot" \
            --git-email "Group.CH_Open-Source@baloise.ch" \
            --organisation "baloise-incubator" \
            --repository-name "okd4-example-apps" \
            --file "baloise-design-system-docs-test/values.yaml" \
            --values "{baloise-design-system-docs.image.tag: ${{ steps.vars.outputs.sha_short }}}"
