name: Visual Regression Test - Base Image

on:
  workflow_dispatch:

jobs:
  CreateBaseImages:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: Update npm registry
        run: npm run registry

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Install Cypress
        run: npm run cy:install

      - name: Run Cypress
        uses: cypress-io/github-action@v4
        with:
          build: npm run cy:build
          start: npm run cy:start
          wait-on: 'http://localhost:3333'
          working-directory: packages/components
          install: false
          browser: chrome
          env: type=base
          spec: |
            cypress/e2e/visual/*.cy.ts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload snapshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-snapshots
          path: packages/components/cypress/snapshots
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit base images
        uses: EndBug/add-and-commit@v9
        with:
          message: 'chore(): update base images'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
